Repository werryxgames/Messaje, pull requests merged in 2023-08, with the labels that each got.

#13 Updated README, "Don't use in production" section
  README.md
Labels: documentation

#16 Make AES key overridable by properties configuration
  .gitignore
  README.md
  android/build.gradle
  android/proguard-rules.pro
  config/client.example.properties
  config/server.example.properties
  core/src/com/werryxgames/messaje/DefaultScreen.java
  core/src/com/werryxgames/messaje/Messaje.java
  server/src/com/werryxgames/messaje/Server.java
  shared/src/com/werryxgames/messaje/Aes.java
  shared/src/com/werryxgames/messaje/Config.java
Labels: documentation, enhancement

#19 Add contacts screen
  assets/icons/icon128.png
  assets/icons/icon16.png
  assets/icons/icon196.png
  assets/icons/icon24.png
  assets/icons/icon256.png
  assets/icons/icon32.png
  assets/icons/icon48.png
  assets/icons/icon512.png
  assets/icons/icon64.png
  assets/icons/received_message.png
  assets/icons/sent_message.png
  core/src/com/werryxgames/messaje/ContactsScreen.java
  core/src/com/werryxgames/messaje/DefaultScreen.java
  core/src/com/werryxgames/messaje/FormattedMessage.java
  core/src/com/werryxgames/messaje/FormattedText.java
  core/src/com/werryxgames/messaje/LoginScreen.java
  core/src/com/werryxgames/messaje/TextPart.java
  desktop/src/com/werryxgames/messaje/DesktopLauncher.java
  server/src/com/werryxgames/messaje/Client.java
  server/src/com/werryxgames/messaje/Database.java
  shared/src/com/werryxgames/messaje/ByteSerializable.java
  shared/src/com/werryxgames/messaje/Config.java
  shared/src/com/werryxgames/messaje/Message.java
  shared/src/com/werryxgames/messaje/User.java
Labels: enhancement

#29 dev
  config/client.example.properties
  core/src/com/werryxgames/messaje/Client.java
  core/src/com/werryxgames/messaje/ContactsScreen.java
  core/src/com/werryxgames/messaje/DefaultScreen.java
  core/src/com/werryxgames/messaje/ErrorDialog.java
  core/src/com/werryxgames/messaje/LoginScreen.java
  core/src/com/werryxgames/messaje/SocketScreen.java
  core/src/com/werryxgames/messaje/UiStyle.java
  server/src/com/werryxgames/messaje/Client.java
  server/src/com/werryxgames/messaje/Database.java
  shared/src/com/werryxgames/messaje/Aes.java
  shared/src/com/werryxgames/messaje/Utils.java
Labels: bug, enhancement

#31 Updated to 1.0
  README.md
Labels: documentation
